In [1]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Python (Numpy)

In [4]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
a * 3

array([3, 6, 9])

# Math Functions

In [7]:
np.sum(a)

6

In [8]:
np.mean(a)

2.0

In [9]:
np.std(a)

0.816496580927726

In [10]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [13]:
np.arange(0, 5, 1.5)

array([0. , 1.5, 3. , 4.5])

In [14]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [70]:
np.random.rand(3, 2)

array([[0.23271893, 0.78152354],
       [0.76953232, 0.62050877],
       [0.03265925, 0.55931326]])

# Controlled Randomness

In [114]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])